### ISSUE TITLE
WFM tracker doesn't pick up changed orders

### ISSUE THREAD

**Issue by Kaptard** [nexus-devs/NexusHub#198]
**I'm submitting a...**

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request

<br>

**Current behavior**

Doesn't update orders when they're changed.

<br>

**Expected behavior**

Should check for updates on price/amount/etc

<br>

**Minimal reproduction of the problem**

Make an order on wfm, change it, check on nexus.

<br>

**Environment**

Browser: 
- [ ] Chrome (desktop) version:
- [ ] Chrome (Android) version:
- [ ] Chrome (iOS) version:
- [ ] Firefox version:
- [ ] Safari (desktop) version:
- [ ] Safari (iOS) version:
- [ ] IE version:
- [ ] Edge version:

For development issues:
- Node version:
- Operating System:

##

**Additional Description**

**Comment by Kaptard** [comment]
fixed in feat/ui-order-selection branch
