### ISSUE TITLE
Refactor meta tags

### ISSUE THREAD

**Issue by Kaptard** [nexus-devs/NexusHub#259]
**I'm submitting a...**

- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [x] Refactor target

<br>

**Current behavior**

Gotta write all meta tags and their prop names in every single component.

<br>

**Expected behavior**

Should have  a function that takes only the content params and autogenerates the meta tags.

<br>

**Minimal reproduction of the problem**

The issue is that there's *a lot* of repeating yourself with the current structure. 
Also given the nature of the content, it would be easy for someone to forget combinations like `og:image` with `itemprop=image`. This refactor would allow you to not think about all these tiny things.

<br>

**Environment**

Browser: 
- [ ] Chrome (desktop) version:
- [ ] Chrome (Android) version:
- [ ] Chrome (iOS) version:
- [ ] Firefox version:
- [ ] Safari (desktop) version:
- [ ] Safari (iOS) version:
- [ ] IE version:
- [ ] Edge version:

For development issues:
- Node version:
- Operating System:

##

**Additional Description**

**Comment by Kaptard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [refactor(seo): Refactor meta tags into generator function](https://trello.com/c/IJj4ICU9/24-refactorseo-refactor-meta-tags-into-generator-function)
