### ISSUE TITLE
Timeline event milestones

### ISSUE THREAD

**Issue by LiMeijdam** [nexus-devs/NexusHub#67]
**I'm submitting a...**

- [ ] Bug report  
- [x] Feature request
- [ ] Documentation issue or request

**Current behavior**

At the moment there is no form of event/ patch visualisation or filtering. There is a feature for time filtering but that is not exactly the same. 

**Expected behavior**

An event or patch should be linked to a fixed date, this date could be visualised in graphs as a milestone. 

**Minimal reproduction of the problem**

When a user for example wants to pricecheck a item that got unvaulted recently, he will see the unvaulting as an event on the price timeline and he will also be able to quickly understand that the change in price is due to the unvaulting event.

**Environment**

Browser: 
- [x] Chrome (desktop) version:
- [ ] Chrome (Android) version:
- [ ] Chrome (iOS) version:
- [x] Firefox version:
- [x] Safari (desktop) version:
- [ ] Safari (iOS) version:
- [x] IE version:
- [x] Edge version:

I am not sure if this function would be supported by mobile browsers as this could be quite the "Intense" feature

For development issues:
- Node version: NA
- Operating System: NA

##

**Additional Description**

Feel free to ask me questions about this feature idea 
Lieuwe_meijdam@hotmail.com

**Comment by Kaptard** [comment]
Might be done alongside #57 . I'd definitely also suggest this being the basis for a more general history state of each item, so we can display changes contextually as they make sense. Added to Post-Rework Ehancements if the effort is too significant for an MVP of the rework, especially on the API-side of things.

**Comment by Kaptard** [comment]
Item patchlogs will be added in the [warframe-items](https://github.com/nexus-devs/warframe-items) repo. That should mostly fix the API concerns.
